### ISSUE TITLE
Resolve Lucene version conflict in Matlab Client

### ISSUE THREAD

**Issue by csjx** [DataONEorg/sem-prov-design#187]
We're getting the following error in Matlab R2015b
```
Warning: A Java exception occurred getting the method description for the java.lang.String class:
Java exception occurred:
java.lang.NoSuchMethodError:
org.apache.lucene.store.FSDirectory.open(Ljava/io/File;)Lorg/apache/lucene/store/FSDirectory;
	at com.mathworks.search.lucene.FileSystemIndexLocation.buildDirectory(FileSystemIndexLocation.java:39)
	at com.mathworks.search.lucene.FileSystemIndexLocation.<init>(FileSystemIndexLocation.java:24)
	at
        com.mathworks.mlwidgets.help.functionregistry.UnlicensedFunctionRegistry.<init>(UnlicensedFunctionRegistry.java:44) 
In org.dataone.client.v2.DataONEClient.getMN (line 52) 
```
I think the lucene-core jar we a re shipping conflicts with the Matlab version.

**Comment by csjx** [comment]
It looks the foresite 1.0 library requires lucene 2.2.0, and Matlab ships with at least lucene 4.6.x (hard to tell since the jar isn't versioned, but the contents suggest this). For now, I've removed the jar from being installed (but we still ship it until we can test all of the repurcussions of the version upgrade from the foresite perspective.)

**Comment by csjx** [comment]
I haven't seen issues with this, so will close it.  Will reopen if we have Foresite issues.
